# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170813_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbean',
            old_name='username',
            new_name='name',
        ),
    ]
